### ISSUE TITLE
Setup Project's Kanban Board

### ISSUE THREAD

**Issue by brenoxav** [brenoxav/space-travelers-hub#25]
## Setup Project's Kanban Board

- Copy the tasks from the template using the given script
- Link to the project: https://github.com/brenoxav/space-travelers-hub/projects/1
- We are a team of two
- **The project's link was updated.**

**Comment by vichuge** [comment]
# Project invalidated 🚫 

Hi there, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![cat_massage](https://user-images.githubusercontent.com/20563252/121368971-16d2dc00-c901-11eb-9123-7f578bf64118.gif)

## Why does this happen ❓ ❓ ❓ 

You have submitted a project, that doesn't have the link to the project, in this case, the link should be https://github.com/brenoxav/space-travelers-hub/projects/1

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brenoxav** [comment]
Thank you for the review, @vichuge !

> You have submitted a project, that doesn't have the link to the project, in this case, the link should be https://github.com/brenoxav/space-travelers-hub/projects/1

You are right! Our mistake.
We have updated the link and re-submited for review.

Thank you!

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
